### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by mwittig** [treban/pimatic-xmpp#1]
In some cases the plugin raises an uncaught exception. See https://forum.pimatic.org/topic/2838/xmpp-problem for details

**Comment by treban** [comment]
Sorry for the late response. I will look at it...

**Comment by treban** [comment]
With release 0.0.8 it should be fixed

**Comment by heiko1988** [comment]
hi,
I have replay in this forum
https://forum.pimatic.org/topic/2838/xmpp-problem

i have a new error :)

Thank you

**Comment by heiko1988** [comment]
Work all fine :) with update xmpp 0.0.10
Hi, thanks for fast update.

**Comment by treban** [comment]
Perfect
